/*
 * Project Euler problem 2
 * https://projecteuler.net/problem=2
 *
 * Each new term in the Fibonacci sequence is generated by adding 
 * the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed 
 * four million, find the sum of the even-valued terms
 */
package java_euler;

/**
 *
 * @author Scott
 * This will loop through the Fibonacci numbers less than 4,000,000
 * and sum the even terms
 */
public class PE_2 {
    public static void euler_2() {    
        int cumulative_sum = 0;
        int fib1 = 1;
        int fib2 = 1;
        int holding;
        while (fib2 <4000000){  // loop through all numbers less than 4e6              
            if (fib2%2 == 0 ) {  // look for even Fibonacci numbers
               cumulative_sum+= fib2;
            }
            holding = fib2;
            fib2 = fib1 + fib2;
            fib1 = holding;            
        }
        
        System.out.println("Problem 2 :" + cumulative_sum);               
        
    }
    
}
